fragment PagesParts on Pages {
  __typename
  ... on PagesHomepage {
    pageName
    kicker
    titleMain
    titleItalic
    subtitle
    heroImage
    intro1Title
    intro1Text
    intro2Title
    intro2Text
    intro3Title
    intro3Text
    profileImage
    aboutTitle
    aboutText1
    aboutText2
    servicesHeading
    newsHeading
    ctaTitle
    ctaDescription
  }
  ... on PagesAbout {
    pageName
    title
    intro
    sharedImage
    sharedImageAlt
    sharedKicker
    sharedIntro
    sharedContent
    hildeImage
    hildeKicker
    hildeTitle
    hildeContent
    hildeKeywords {
      __typename
      keyword
    }
    tinaMariaImage
    tinaMariaKicker
    tinaMariaTitle
    tinaMariaContent
    tinaMariaKeywords {
      __typename
      keyword
    }
    valuesTitle
    value1Title
    value1Text
    value2Title
    value2Text
    value3Title
    value3Text
    ctaTitle
    ctaDescription
  }
  ... on PagesStandard {
    pageName
    title
    intro
    ctaTitle
    ctaDescription
  }
  ... on PagesKontakt {
    title
    kicker
    heading
    description
    addressLine1
    addressLine2
    addressLine3
    email
    phone
  }
}

fragment ServicesParts on Services {
  __typename
  title
  category
  tagline
  image
  description
  offers {
    __typename
    title
    price
  }
  order
}

fragment ArticlesParts on Articles {
  __typename
  title
  excerpt
  author
  date
  category
  readingTime
  coverImage
  body
}

fragment EventsParts on Events {
  __typename
  title
  description
  image
  date
  endDate
  host
  time
  location
  spots
  tags
  price
}

fragment EventCategoriesParts on EventCategories {
  __typename
  value
  label
}
