fragment PagesParts on Pages {
  __typename
  ... on PagesHomepage {
    pageName
    kicker
    titleMain
    titleItalic
    subtitle
    heroImage
    intro1Title
    intro1Text
    intro2Title
    intro2Text
    intro3Title
    intro3Text
    profileImage
    aboutTitle
    aboutText1
    aboutText2
    servicesHeading
    newsHeading
    ctaTitle
    ctaDescription
  }
  ... on PagesAbout {
    pageName
    title
    intro
    sharedImage
    sharedImageAlt
    sharedKicker
    sharedIntro
    sharedContent
    hildeImage
    hildeKicker
    hildeTitle
    hildeContent
    hildeKeywords
    tinaMariaImage
    tinaMariaKicker
    tinaMariaTitle
    tinaMariaContent
    tinaMariaKeywords
    valuesTitle
    value1Title
    value1Text
    value2Title
    value2Text
    value3Title
    value3Text
    ctaTitle
    ctaDescription
  }
  ... on PagesStandard {
    pageName
    title
    intro
    ctaTitle
    ctaDescription
  }
  ... on PagesContact {
    pageName
    facebook
    instagram
    hildeName
    hildeEmail
    hildePhone
    hildeHomePage
    tinaName
    tinaEmail
    tinaPhone
    tinaHomePage
  }
}

fragment ServicesParts on Services {
  __typename
  title
  category
  tagline
  image
  description
  offers {
    __typename
    title
    price
  }
  order
}

fragment ArticlesParts on Articles {
  __typename
  title
  excerpt
  author
  date
  category
  coverImage
  body
}

fragment EventsParts on Events {
  __typename
  title
  description
  image
  date
  endDate
  host
  time
  location
  spots
  category {
    ... on EventCategories {
      __typename
      value
      label
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  tags
  price
}

fragment EventCategoriesParts on EventCategories {
  __typename
  value
  label
}
