fragment PagesParts on Pages {
  __typename
  ... on PagesHomepage {
    kicker
    titleMain
    titleItalic
    subtitle
    heroImage
    intro1Title
    intro1Text
    intro2Title
    intro2Text
    intro3Title
    intro3Text
    profileImage
    aboutTitle
    aboutText1
    aboutText2
    servicesHeading
    newsHeading
    ctaTitle
    ctaDescription
  }
  ... on PagesAbout {
    title
    intro
    sharedImage
    sharedImageAlt
    sharedKicker
    sharedIntro
    sharedContent
    hildeImage
    hildeKicker
    hildeIntro
    hildeContent
    keywords {
      __typename
      keyword
    }
    verdier {
      __typename
      tittel
      tekst
    }
  }
  ... on PagesStandard {
    title
    subtitle
    intro
    profileImage
    body
    contactName
    contactLocation
    contactEmail
    verdier {
      __typename
      tittel
      tekst
    }
  }
  ... on PagesHeader {
    title
    intro
  }
  ... on PagesServices {
    title
    subtitle
    intro
    infoBadge
    faq {
      __typename
      question
      answer
    }
  }
  ... on PagesKontakt {
    title
    kicker
    heading
    description
    addressLine1
    addressLine2
    addressLine3
    email
    phone
  }
}
